motech-implementations/nms

- api/src/test/java/org/motechproject/nms/api/osgi/CallDetailsControllerBundleIT.java
- api/src/test/java/org/motechproject/nms/api/osgi/KilkariControllerBundleIT.java
- api/src/test/java/org/motechproject/nms/api/osgi/LanguageControllerBundleIT.java
- api/src/test/java/org/motechproject/nms/api/osgi/UserControllerBundleIT.java
- flw/src/main/java/org/motechproject/nms/flw/domain/FrontLineWorker.java
- flw/src/main/java/org/motechproject/nms/flw/service/FrontLineWorkerService.java
- flw/src/main/java/org/motechproject/nms/flw/service/impl/FrontLineWorkerServiceImpl.java
- flw/src/test/java/org/motechproject/nms/flw/osgi/FrontLineWorkerServiceBundleIT.java
- flw/src/test/java/org/motechproject/nms/flw/osgi/IntegrationTests.java
- flw/src/test/java/org/motechproject/nms/flw/osgi/ServiceUsageServiceBundleIT.java
- imi/src/test/java/org/motechproject/nms/imi/it/CdrFileServiceBundleIT.java
- imi/src/test/java/org/motechproject/nms/imi/it/TargetFileServiceBundleIT.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriberService.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriptionService.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
- kilkari/src/test/java/org/motechproject/nms/kilkari/osgi/CsrServiceBundleIT.java
- kilkari/src/test/java/org/motechproject/nms/kilkari/osgi/IntegrationTests.java
- kilkari/src/test/java/org/motechproject/nms/kilkari/osgi/SubscriberServiceBundleIT.java
- kilkari/src/test/java/org/motechproject/nms/kilkari/osgi/SubscriptionServiceBundleIT.java
- kilkari/src/test/java/org/motechproject/nms/kilkari/ut/SubscriptionUnitTest.java
- props/src/test/java/org/motechproject/nms/props/ut/CallDisconnectReasonUnitTest.java
- props/src/test/java/org/motechproject/nms/props/ut/DayOfTheWeekTest.java
- props/src/test/java/org/motechproject/nms/props/ut/FinalCallStatusTest.java
- props/src/test/java/org/motechproject/nms/props/ut/RequestIdUnitTest.java
- props/src/test/java/org/motechproject/nms/props/ut/StatusCodeUnitTest.java
Add a pre-delete lifecycle listener that verifies a subscription has been closed at least 6 weeks
before it can be deleted.
> Fixes #131

- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
- kilkari/src/test/java/org/motechproject/nms/kilkari/osgi/SubscriptionServiceBundleIT.java
If there is a subscriber, but they do not have a language and the subscription does have a
language we assign that language to the user.
> Fixes #268

- kilkari/src/main/java/org/motechproject/nms/kilkari/domain/DeactivationReason.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/domain/MctsBeneficiary.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriptionService.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
- testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java
Deactivate pregnancy subscription if a new child subscription is created via MCTS import with matching mother ID.
> Fixes #112 - deactivate pregnancy subscription

- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
- testing/src/test/java/org/motechproject/nms/testing/it/api/KilkariControllerBundleIT.java
If user calls to subscribe but already has a subscription via MCTS update origin to be IVR
> Fixes #357 - Update subscription origin to IVR if MCTS subscription exists

- kilkari/src/main/java/org/motechproject/nms/kilkari/domain/SubscriptionPackMessage.java
- testing/src/test/java/org/motechproject/nms/testing/it/imi/TargetFileServiceBundleIT.java
- testing/src/test/java/org/motechproject/nms/testing/it/kilkari/SubscriptionServiceBundleIT.java
BBC has clarified for us that the welcome message is the same as the week 1 message (we had previously been using a placeholder of "welcome.wav").
> Using correct file name for welcome message

- imi/src/main/java/org/motechproject/nms/imi/service/impl/ImiServiceId.java
- imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java
- imi/src/main/resources/imi.properties
- testing/src/test/java/org/motechproject/nms/testing/it/imi/TargetFileServiceBundleIT.java
`generateTargetFile` now uses S1 and S2 as `ImiServiceId` field
for MCTS and IVR subscriptions, respectively
> Fixes NIP-56

- imi/src/main/java/org/motechproject/nms/imi/service/impl/CsvHelper.java
If either MsgPlayTime field is missing return the play duration as 0.  These are optional fields.
> Fixes NIP-57

- kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/CsrServiceImpl.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/InboxServiceImpl.java
- testing/src/test/java/org/motechproject/nms/testing/it/imi/TargetFileServiceBundleIT.java
- testing/src/test/java/org/motechproject/nms/testing/it/kilkari/CsrServiceBundleIT.java
- testing/src/test/java/org/motechproject/nms/testing/it/kilkari/InboxServiceBundleIT.java
- testing/src/test/java/org/motechproject/nms/testing/it/kilkari/SubscriptionServiceBundleIT.java
If the user needs the welcome message, set that as the filename.
@llavoie This feels wrong to me.  First, the ticket is hard to follow.  Once it was decided that the actual issue was something different then the description should be updated.  As far as I can tell this "fixes" it.  Although it seems odd that the user will call and only hear the week 1/welcome message when the actual message is week 5 or something else.  Shouldn't we return two messages, the week 1/welcome and the actual message?
> Fixes NIP-60 (really)

- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java
Subscribers via IVR will not have an LMP date.  So we check if one exists before attempting
to update the start date.
> Fixes NIP-65

- kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/repository/SubscriptionDataService.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriptionService.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
When we create a subscription we now set the first and second message date.  When we load
subscriptions at target generation time we decide if we should load only the first message day or first and second message day.
> Fixes NIP-72

- api/src/main/java/org/motechproject/nms/api/web/CallDetailsController.java
- flw/src/main/java/org/motechproject/nms/flw/domain/CallDetailRecord.java
There was confusion since we have callStatus and finalCallStatus in the database.  I don't remember why we have finalCallStatus, but rather then risk breaking something else I'm just preventing MDS from generating a column for callStatus since we don't have any value we will store there.
> For NIP-82

- flw/src/main/java/org/motechproject/nms/flw/domain/FrontLineWorker.java
- flw/src/main/java/org/motechproject/nms/flw/domain/validation/FrontLineWorkerValidator.java
- flw/src/main/java/org/motechproject/nms/flw/service/FrontLineWorkerService.java
- flw/src/main/java/org/motechproject/nms/flw/service/impl/FrontLineWorkerServiceImpl.java
- testing/src/test/java/org/motechproject/nms/testing/it/api/UserControllerBundleIT.java
- testing/src/test/java/org/motechproject/nms/testing/it/flw/FrontLineWorkerImportServiceBundleIT.java
- testing/src/test/java/org/motechproject/nms/testing/it/flw/FrontLineWorkerServiceBundleIT.java
When a user is marked as INVALID we now null out their contact number.  The non-null
constraint in the database has been removed but a class level validator has been added that
enforces a contact number when the status is not INVALID and that contact number is null when
status is INVALID.
Since the INVALID FLW has no contact number there will be no conflict if a user with that number calls MA/MK.
All other information is retained in the record.
> Fixes NMS-236

- imi/src/main/java/org/motechproject/nms/imi/service/impl/ExponentialRetrySender.java
Switch from the javax default to apache's.  The apache version claims to mimic browser hostname verification which checks wildcards.  The javax default is assumed to be called only on a mismatch so it just returns false (I think)
> Change which DefaultHostnameVerifier is used.  

- performance/data/data.py
- testing/src/main/java/org/motechproject/nms/testing/service/TestingService.java
- testing/src/main/java/org/motechproject/nms/testing/service/impl/MctsHelper.java
- testing/src/main/java/org/motechproject/nms/testing/service/impl/TestingServiceImpl.java
- testing/src/main/java/org/motechproject/nms/testing/web/TestingController.java
- testing/src/test/java/org/motechproject/nms/testing/it/testing/BundleIT.java
Calling
```
python ~/src/mim/performance/data/data.py --cleardb --mctsmoms=10000 --lmp
```
with the `--lmp` parameter will generate mothers with a static LMP of 90 days prior to today.
And calling 
```
python ~/src/mim/performance/data/data.py --cleardb --mctskids=10000 --dob
```
with the `--dob` parameter will generate kids with a static DOB of today
> Static LMP & DOB options for test MCTS data

- imi/src/main/java/org/motechproject/nms/imi/service/impl/CdrFileServiceImpl.java
- imi/src/main/java/org/motechproject/nms/imi/web/ImiController.java
- imi/src/main/java/org/motechproject/nms/imi/web/contract/AggregateBadRequest.java
failureReasons => failureReason   (no trailing s)
more verbose log output on error
checksums now case insensitive
> Small fixes from NIP-198 investigation

- imi/src/main/java/org/motechproject/nms/imi/service/CsrValidatorService.java
- imi/src/main/java/org/motechproject/nms/imi/service/impl/CdrFileServiceImpl.java
- imi/src/main/java/org/motechproject/nms/imi/service/impl/CsrValidatorServiceImpl.java
- testing/src/test/java/org/motechproject/nms/testing/it/imi/CsrValidatorServiceBundleIT.java
Invalid subscriptions in phase2 of CDR processing should not cause
an overall rejection, but instead just send an alert & log
> Fixes NIP-202

- imi/src/main/java/org/motechproject/nms/imi/service/impl/ExponentialRetrySender.java
- imi/src/main/java/org/motechproject/nms/imi/service/impl/SmsNotificationServiceImpl.java
- imi/src/main/resources/imi.properties
- Closes the http connection after we get a response back.
- Logs a success response
- Adds a config value that allows the turning on of http timeouts
- Exponential Retry Sender now returns a boolean.  SMS Notification service uses this boolean in the completion record instead of always using true.
> Fixes NIP-209, Fixes NIP-208, Fixes #648, Fixes #647

- api/src/main/java/org/motechproject/nms/api/web/AddFlwRequest.java
- api/src/main/java/org/motechproject/nms/api/web/OpsController.java
- api/src/main/java/org/motechproject/nms/api/web/contract/AddFlwRequest.java
- flw/src/main/java/org/motechproject/nms/flw/domain/FlwError.java
- flw/src/main/java/org/motechproject/nms/flw/domain/FlwErrorReason.java
- flw/src/main/java/org/motechproject/nms/flw/repository/FlwErrorDataService.java
- flw/src/main/java/org/motechproject/nms/flw/service/FrontLineWorkerService.java
- flw/src/main/java/org/motechproject/nms/flw/service/impl/FrontLineWorkerImportServiceImpl.java
- flw/src/main/java/org/motechproject/nms/flw/service/impl/FrontLineWorkerServiceImpl.java
- flw/src/main/java/org/motechproject/nms/flw/utils/FlwConstants.java
- flw/src/main/java/org/motechproject/nms/flw/utils/FlwMapper.java
- flw/src/main/resources/META-INF/spring/blueprint.xml
- region/src/main/java/org/motechproject/nms/region/service/LocationService.java
- region/src/main/java/org/motechproject/nms/region/service/impl/LocationServiceImpl.java
- testing/src/main/java/org/motechproject/nms/testing/service/impl/TestingServiceImpl.java
- testing/src/test/java/org/motechproject/nms/testing/it/IntegrationTests.java
- testing/src/test/java/org/motechproject/nms/testing/it/api/OpsControllerBundleIT.java
- testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryUpdateServiceBundleIT.java
- testing/src/test/resources/csv/mcts_beneficiary_update.csv
This implements an ops hook to consume NIC data from an http client with specific fields in a contract. This helps sync up one-time db dumps to make up for MCTS service availability (lack of)
> Consume NIC dump

- kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriberService.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java
Fixed a couple of bugs
1. CaseId was not being imported into the db in one case even though we were getting data in xml file.
2. Made changes to update mother and subscriber tables only if an update for a mother was accepted (previously, in a few cases, some fields in the mother table were being updated even if the record was rejected, leading to a mismatch in data between the mother and subscriber tables).
> Case id null bug fix

- kilkari/src/main/java/org/motechproject/nms/kilkari/service/ChildCsvThreadProcessor.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/MotherCsvThreadProcessor.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryValueProcessorImpl.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/utils/KilkariConstants.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/utils/MctsBeneficiaryUtils.java
- mcts/src/main/java/org/motechproject/nms/mcts/service/impl/MctsWsImportServiceImpl.java
**Issue1:**
The existing code allow line break(\n,\t,\r, white space) in the list of ids
Eg:Import record 1 with above special char then import update for same record but this time id doesn't contain special char, In this scenario system treating this id as new Id but both ids are same in the term of numerical digits.
**After fix expected behavior:** 
This fix will remove new Line('\n'), white space(' '), tab('\t'), '\r' form the give ids (table) before processing to DB,
Eg: if we import record with id="12 24\t5\n\t"
then system will save the record with id=12245
**Issue2**
creating a rch mother record with rch id r1 and mcts id=null
update the mother record with rch id r1 and mcts id m1
Expected result=> should update the mcts id in mother record
Actual Result=> Reject the mother record …
> Data Integrity error fix and id cleanup

- rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/ChildRejectionServiceImpl.java
- rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/MotherRejectionServiceImpl.java
If registrationdate date tag is missing from xml for mother and child, the values recorded as 'null' as string, which causing issue in ETL, resolved issue, now for above scenario values are recorded as NULL
> Bug fix : Registration date 'null' as string

- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java
Contain 3 bugs fixes. Rejected record should not update mcts table. Active child should not get replaced with another child. Future exec date should get rejected
> Rejected record updating mcts

- kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriptionService.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java
- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
LMP/ DOB and mobile number update should delete the record from retry table. It should prevent it from having a new record in case update came first before CSR and CDR
> Any update regarding subscriber should delete record from retry table

- kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
- mobile-academy/src/main/resources/sms-content.properties
- rch/src/main/java/org/motechproject/nms/rch/service/impl/RchWsImportServiceImpl.java
- rch/src/main/resources/rch.properties
Scp of file from web servers to DB server
> SCP with multiple retries of file from web to db
