api/src/test/java/org/motechproject/nms/api/osgi/HelloWorldWebBundleIT.java, flw/src/test/java/org/motechproject/nms/flw/osgi/HelloWorldWebBundleIT.java, kilkari/src/test/java/org/motechproject/nms/kilkari/osgi/HelloWorldWebBundleIT.java, mobile-academy/src/test/java/org/motechproject/nms/mobileacademy/osgi/HelloWorldWebBundleIT.java, mobile-kunji/src/test/java/org/motechproject/nms/mobilekunji/osgi/HelloWorldWebBundleIT.java, pom.xml
I made the master pom.xml to be more like that of the current modules (master branch: 0.26) master pom.xml and voila.
=> Now builds with master (0.26-SNAPSHOT)

api/src/main/java/org/motechproject/nms/api/web/BaseController.java, api/src/main/java/org/motechproject/nms/api/web/KilkariController.java, api/src/main/java/org/motechproject/nms/api/web/UserController.java, api/src/main/java/org/motechproject/nms/api/web/contract/InboxSubscriptionDetail.java, api/src/main/java/org/motechproject/nms/api/web/contract/KilkariResponseInbox.java, api/src/main/java/org/motechproject/nms/api/web/contract/SubscriptionRequest.java, api/src/main/java/org/motechproject/nms/api/web/exception/NotFoundException.java, api/src/test/java/org/motechproject/nms/api/osgi/IntegrationTests.java, api/src/test/java/org/motechproject/nms/api/osgi/KilkariControllerBundleIT.java, api/src/test/java/org/motechproject/nms/api/osgi/UserControllerBundleIT.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscriber.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java, kilkari/src/main/java/org/motechproject/nms/kilkari/repository/SubscriptionDataService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/KilkariService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/KilkariServiceImpl.java, kilkari/src/main/resources/META-INF/spring/blueprint.xml, kilkari/src/test/java/org/motechproject/nms/kilkari/osgi/KilkariServiceBundleIT.java
Implemented the GetInboxDetails API in the API module, and some of the plumbing in Kilkari
(including adding a Subscription entity and refactoring existing Subscriber/SubscriptionPack
code a bit). The inboxWeekId and contentFileName are hard-coded to bogus values for now.
=> Issue #9 - Get Inbox Details

api/pom.xml, api/src/main/java/org/motechproject/nms/api/web/BaseController.java, api/src/main/java/org/motechproject/nms/api/web/KilkariController.java, api/src/main/java/org/motechproject/nms/api/web/UserController.java, api/src/main/java/org/motechproject/nms/api/web/contract/CallDisconnectReason.java, api/src/main/java/org/motechproject/nms/api/web/contract/CallStatus.java, api/src/main/java/org/motechproject/nms/api/web/contract/LanguageRequest.java, api/src/main/java/org/motechproject/nms/api/web/contract/kilkari/InboxCallDetailsRequest.java, api/src/main/java/org/motechproject/nms/api/web/contract/kilkari/InboxCallDetailsRequestCallData.java, api/src/main/java/org/motechproject/nms/api/web/contract/kilkari/InboxResponse.java, api/src/main/java/org/motechproject/nms/api/web/contract/kilkari/InboxSubscriptionDetailResponse.java, api/src/main/java/org/motechproject/nms/api/web/contract/kilkari/UserResponse.java, api/src/test/java/org/motechproject/nms/api/osgi/KilkariControllerBundleIT.java, api/src/test/java/org/motechproject/nms/api/osgi/UserControllerBundleIT.java
But not quite, still needs work.
This is for you @koshalt
=> Partially fix for #12

flw/src/main/java/org/motechproject/nms/flw/domain/CallContent.java, flw/src/main/java/org/motechproject/nms/flw/domain/CallDetailRecord.java, flw/src/main/java/org/motechproject/nms/flw/domain/FrontLineWorker.java, flw/src/main/java/org/motechproject/nms/flw/domain/ServiceUsage.java, flw/src/main/java/org/motechproject/nms/flw/domain/ServiceUsageCap.java, flw/src/main/java/org/motechproject/nms/flw/domain/WhitelistEntry.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/InboxCallData.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/InboxCallDetails.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscriber.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/SubscriptionPack.java, language/src/main/java/org/motechproject/nms/language/domain/CircleLanguage.java, language/src/main/java/org/motechproject/nms/language/domain/Language.java
Set our table names to shorter more permanent names so functional testing can work with them.  Also add cascade deletion for call_content records.
@llavoie Do you want to look at this one.
=> Fixes #61 Fixes #64

api/src/test/java/org/motechproject/nms/api/osgi/CallDetailsControllerBundleIT.java
=> Refactored CallDetailsControlerBundleIT

api/src/main/java/org/motechproject/nms/api/web/KilkariController.java, outbound-dialer/pom.xml, outbound-dialer/src/main/java/org/motechproject/nms/outbounddialer/domain/FileProcessedStatus.java, outbound-dialer/src/main/java/org/motechproject/nms/outbounddialer/web/OutboundDialerController.java, outbound-dialer/src/test/java/org/motechproject/nms/outbounddialer/osgi/OutboundDialerControllerBundleIT.java
Adds more test cases for CDR Notification Request and implements File Processed Request
=> Fixes #13 & fixes #14

api/src/main/java/org/motechproject/nms/api/web/KilkariController.java, api/src/test/java/org/motechproject/nms/api/osgi/KilkariControllerBundleIT.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/DeactivationReason.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriptionService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
Adds a DeactivationReason enum and passes it to deactivateSubscription method
=> Fixes #168 Save Deactivation Reason

kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscriber.java, location/src/main/java/org/motechproject/nms/location/domain/District.java, location/src/main/java/org/motechproject/nms/location/domain/HealthBlock.java, location/src/main/java/org/motechproject/nms/location/domain/HealthFacility.java, location/src/main/java/org/motechproject/nms/location/domain/HealthFacilityType.java, location/src/main/java/org/motechproject/nms/location/domain/HealthSubFacility.java, location/src/main/java/org/motechproject/nms/location/domain/State.java, location/src/main/java/org/motechproject/nms/location/domain/Taluka.java, location/src/main/java/org/motechproject/nms/location/repository/HealthFacilityTypeDataService.java, location/src/main/resources/META-INF/spring/blueprint.xml, location/src/test/java/org/motechproject/nms/location/osgi/LocationServiceBundleIT.java
This adds database constraints and some fields that I think are required.  It is not the complete fix for #99.  I'm still waiting for final word on the location requirements.  I'm also waiting for a fix to the detached field issue.  I would like to merge this so the work doesn't get stale.
=> Interim commit

checkstyle.xml, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscriber.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/SubscriptionMode.java, outbound-dialer/src/main/java/org/motechproject/nms/outbounddialer/domain/AuditRecord.java, outbound-dialer/src/main/java/org/motechproject/nms/outbounddialer/domain/CallRetry.java, outbound-dialer/src/main/java/org/motechproject/nms/outbounddialer/service/impl/CdrFileServiceImpl.java, outbound-dialer/src/main/java/org/motechproject/nms/outbounddialer/service/impl/SettingsServiceImpl.java, outbound-dialer/src/main/java/org/motechproject/nms/outbounddialer/service/impl/TargetFileServiceImpl.java, outbound-dialer/src/main/java/org/motechproject/nms/outbounddialer/web/OutboundDialerController.java, outbound-dialer/src/main/resources/outbound-dialer.properties, outbound-dialer/src/test/java/org/motechproject/nms/outbounddialer/it/TargetFileServiceBundleIT.java, pmd.xml
and also dismisses magic number PMD errors in annotations (ie: mostly column widths)
=> Complete file format for targetFile

api/src/main/java/org/motechproject/nms/api/web/converter/MobileAcademyConverter.java, api/src/test/java/org/motechproject/nms/api/osgi/MobileAcademyControllerBundleIT.java, api/src/test/java/org/motechproject/nms/api/utils/CourseBuilder.java, mobile-academy/pom.xml
fixing the build break in master
=> Adding dependency and ignoring unreliable test

mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/MobileAcademyServiceImpl.java
Didn't realize that the earlier pr was merged already. minor change.
=> More refactor from CR

imi/src/main/java/org/motechproject/nms/imi/component/CallRescheduler.java, imi/src/main/java/org/motechproject/nms/imi/component/SubscriptionCompleter.java, imi/src/main/java/org/motechproject/nms/imi/service/impl/CdrFileServiceImpl.java, imi/src/test/java/org/motechproject/nms/imi/it/CdrFileServiceBundleIT.java, imi/src/test/java/org/motechproject/nms/imi/it/CdrHelper.java, imi/src/test/java/org/motechproject/nms/imi/it/ImiController_CDR_BundleIT.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriptionService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java, kilkari/src/test/java/org/motechproject/nms/kilkari/ut/SubscriptionUnitTest.java
The status of a subscription will change to completed during the CDR
processing when the last message has been successfully played (or not)
=> Fixes #166

kilkari/src/main/java/org/motechproject/nms/kilkari/domain/CallRetry.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java, kilkari/src/test/java/org/motechproject/nms/kilkari/osgi/SubscriptionServiceBundleIT.java
Created an IT that verifies you can reactivate a DND subscription with IVR
=> Fixes #182

api/src/main/java/org/motechproject/nms/api/web/MobileAcademyController.java, api/src/test/java/org/motechproject/nms/api/osgi/MobileAcademyControllerBundleIT.java, api/src/test/java/org/motechproject/nms/api/ut/MobileAcademyControllerUnitTest.java, mobile-academy/pom.xml, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/domain/CompletionRecord.java, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/exception/CourseNotCompletedException.java, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/MobileAcademyService.java, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/MobileAcademyServiceImpl.java, mobile-academy/src/test/java/org/motechproject/nms/mobileacademy/it/MobileAcademyServiceBundleIT.java, mobile-academy/src/test/java/org/motechproject/nms/mobileacademy/ut/MobileAcademyServiceUnitTest.java
=> Trigger course completion notification

flw/src/main/java/org/motechproject/nms/flw/service/impl/WhitelistServiceImpl.java, flw/src/main/resources/META-INF/spring/blueprint.xml, flw/src/test/java/org/motechproject/nms/flw/osgi/WhiteListServiceBundleIT.java
The check for whitelist being enabled for a state was looking in the wrong table.
=> Fixes #253

api/src/main/java/org/motechproject/nms/api/web/UserController.java
We want GetSubscriberDetails to only return ACTIVE/PENDING subscriptions, not DEACTIVATED or COMPLETED.
=> fixing small bug in Kilkari GetSubscriberDetails

pom.xml
=> Removed pax-exam dependency

testing/src/test/java/org/motechproject/nms/testing/it/kilkari/CsrServiceBundleIT.java
FT cases 150  added.
@PriyaJain5 : Follow same naming convention while creating a branch
=> Added test case NMS_FT_150 in branch aricent_FT_150.

testing/src/test/java/org/motechproject/nms/testing/it/kilkari/CsrServiceBundleIT.java
=> added test case NMS_FT_138, NMS_FT_139 on NMS.FT.138.139 branch.

testing/src/test/java/org/motechproject/nms/testing/it/api/KilkariControllerBundleIT.java
Implemented test case NMS_FT_77
=> Implemnted test case NMS_FT_77

flw/src/main/java/org/motechproject/nms/flw/domain/FrontLineWorker.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscriber.java
No personal information like name,mobileno,dob,lmp are logged currently.
Though,its better to remove them from toString method which cuts down the possibility of such information to be logged substantially.
=> NMS.GEN.SECU.004

mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/MobileAcademyServiceImpl.java, mobile-academy/src/test/java/org/motechproject/nms/mobileacademy/ut/MobileAcademyServiceUnitTest.java, testing/src/test/java/org/motechproject/nms/testing/it/ma/MobileAcademyServiceBundleIT.java
Fixes #245 
Fetching a bookmark after completion will reset it. This is based on confirmation from BBC
=> 245 course completion

flw/src/main/java/org/motechproject/nms/flw/service/impl/FrontLineWorkerServiceImpl.java, flw/src/main/resources/flw.properties, imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java, imi/src/main/resources/imi.properties, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java, kilkari/src/main/resources/kilkari.properties
=> Fixing build break caused by RepeatingSchedulableJob API change

testing/pom.xml, testing/src/test/resources/bootstrap.properties, testing/src/test/resources/motech-settings.properties
Makes sure that we use resources from testing project for IT runs
=> Fixing bin place for test resources

testing/src/test/java/org/motechproject/nms/testing/it/kilkari/SubscriptionServiceBundleIT.java
Added Implementation of NMS_FT_156, NMS_FT_159, NMS_FT_160 with the method verifyFT156, verifyFT159, verifyFT160 respectivly.
=> Added Implementation of NMS_FT_156, NMS_FT_159, NMS_FT_160

api/pom.xml, csv/pom.xml, flw/pom.xml, imi/pom.xml, kilkari/pom.xml, mobile-academy/pom.xml, props/pom.xml, region/pom.xml, testing/pom.xml, testing/src/test/java/org/motechproject/nms/testing/it/IntegrationTests.java, testing/src/test/java/org/motechproject/nms/testing/it/imi/CdrFileServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/imi/CsrValidatorServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/imi/ImiController_CDR_BundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/imi/ImiController_OBD_BundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/imi/ImiTestHelper.java, testing/src/test/java/org/motechproject/nms/testing/it/imi/TargetFileServiceBundleIT.java
- This disables the IMI ITs. Tagging #381 for followup.
- Cleans up duplicate dependencies in child poms
=> Disabling tests for IMI

testing/src/test/java/org/motechproject/nms/testing/it/kilkari/SubscriptionServiceBundleIT.java
Made new branch named SubscriptionServiceBundleIT and merged branch NMS.FT.132.133.134, NMS.FT.153, NMS.FT.182 into SubscriptionServiceBundleIT branch
=> Subscription service bundle it

api/src/main/java/org/motechproject/nms/api/web/BaseController.java, testing/src/test/java/org/motechproject/nms/testing/it/api/UserControllerBundleIT.java
Fix for JIRA ticket "https://applab.atlassian.net/browse/NMS-192"
=> JIRA issue 192 fix

testing/src/test/java/org/motechproject/nms/testing/it/api/KilkariControllerBundleIT.java
Kilkari Api test cases merged in this branch for review.
=> Nms.ft.kilkaricontrollerit

testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java
Added test-case for mcts upload
=> Nms.ft.mcts beneficiary import service bundle it

region/src/main/java/org/motechproject/nms/region/service/StateImportService.java, region/src/main/java/org/motechproject/nms/region/service/impl/StateImportServiceImpl.java, region/src/main/resources/META-INF/spring/blueprint.xml, testing/src/test/java/org/motechproject/nms/testing/it/region/LocationDataImportServiceBundleIT.java, testing/src/test/resources/csv/census_village.csv, testing/src/test/resources/csv/district.csv, testing/src/test/resources/csv/health_block.csv, testing/src/test/resources/csv/health_facility.csv, testing/src/test/resources/csv/health_sub_facility.csv, testing/src/test/resources/csv/non_census_village_associated.csv, testing/src/test/resources/csv/non_census_village_non_associated.csv, testing/src/test/resources/csv/state.csv, testing/src/test/resources/csv/taluka.csv
=> State CSV import

testing/src/test/java/org/motechproject/nms/testing/it/region/LanguageLocationCodesImportServiceBundleIT.java
Added test cases for languageLocationCode CSV.
=> Added test cases for languageLocationCode CSV.

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/LocationService.java, region/src/main/java/org/motechproject/nms/region/service/VillageService.java, region/src/main/java/org/motechproject/nms/region/service/impl/LocationServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/VillageServiceImpl.java
@frankhuster all yours :smile:
=> Updated with CR feedback

flw/pom.xml
Re-doing PR #417 so that it may be tested via our CI
=> Resubmitting tstalka's fix for incorrect module assigned to entities

testing/src/test/java/org/motechproject/nms/testing/it/kilkari/InboxServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/SubscriptionServiceBundleIT.java
Remove ignore annotation over the test cases as the issues mentioned are resolved now.
=> NMS-190 ,201

api/src/main/java/org/motechproject/nms/api/web/BaseController.java, api/src/main/java/org/motechproject/nms/api/web/CallDetailsController.java, api/src/main/java/org/motechproject/nms/api/web/KilkariController.java, api/src/main/java/org/motechproject/nms/api/web/LanguageController.java, api/src/main/java/org/motechproject/nms/api/web/MobileAcademyController.java, api/src/main/java/org/motechproject/nms/api/web/UserController.java, api/src/main/java/org/motechproject/nms/api/web/contract/CallDetailRecordRequest.java, api/src/main/java/org/motechproject/nms/api/web/contract/LogHelper.java, api/src/main/java/org/motechproject/nms/api/web/contract/UserLanguageRequest.java, api/src/main/java/org/motechproject/nms/api/web/contract/kilkari/InboxCallDetailsRequest.java, api/src/main/java/org/motechproject/nms/api/web/contract/kilkari/SubscriptionRequest.java, api/src/main/java/org/motechproject/nms/api/web/contract/mobileAcademy/SaveBookmarkRequest.java, api/src/main/java/org/motechproject/nms/api/web/contract/mobileAcademy/SmsStatusRequest.java, api/src/main/java/org/motechproject/nms/api/web/contract/mobileAcademy/sms/DeliveryInfo.java, api/src/main/java/org/motechproject/nms/api/web/contract/mobileAcademy/sms/DeliveryInfoNotification.java, api/src/main/java/org/motechproject/nms/api/web/contract/mobileAcademy/sms/RequestData.java, api/src/test/java/org/motechproject/nms/api/ut/LogHelperUnitTest.java, imi/src/main/java/org/motechproject/nms/imi/web/ImiController.java
=> #141 - IVR Interaction logging w/o PII

mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/MobileAcademyServiceImpl.java, mobile-academy/src/main/resources/META-INF/spring/blueprint.xml, mobile-academy/src/test/java/org/motechproject/nms/mobileacademy/ut/MobileAcademyServiceUnitTest.java, testing/src/test/java/org/motechproject/nms/testing/it/ma/MobileAcademyServiceBundleIT.java
Helps track the course completion count for a user.
=> Adding a way to track completion count for MA

api/src/main/java/org/motechproject/nms/api/web/BaseController.java, imi/src/main/java/org/motechproject/nms/imi/web/ImiController.java
=> CR feedback

imi/src/main/java/org/motechproject/nms/imi/service/impl/CdrFileServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/dto/CallSummaryRecordDto.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/CsrServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/imi/CdrFileServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/utils/CdrHelper.java
=> Fixes NMS-216

csv/src/main/java/org/motechproject/nms/csv/utils/CsvInstanceImporter.java, testing/src/test/java/org/motechproject/nms/testing/it/region/LocationDataImportServiceBundleIT.java
Track the column number so it can be printed in the error message
=> Fixes NMS-213

csv/pom.xml, csv/src/main/java/org/motechproject/nms/csv/domain/CsvAuditRecord.java, csv/src/main/java/org/motechproject/nms/csv/repository/CsvAuditRecordDataService.java, csv/src/main/java/org/motechproject/nms/csv/service/CsvAuditService.java, csv/src/main/java/org/motechproject/nms/csv/service/impl/CsvAuditServiceImpl.java, csv/src/main/resources/META-INF/spring/blueprint.xml, flw/src/main/java/org/motechproject/nms/flw/web/FrontLineWorkerImportController.java, flw/src/main/resources/META-INF/spring/blueprint.xml, kilkari/src/main/java/org/motechproject/nms/kilkari/web/MctsBeneficiaryImportController.java, kilkari/src/main/resources/META-INF/spring/blueprint.xml, region/src/main/java/org/motechproject/nms/region/controller/LanguageLocationImportController.java, region/src/main/java/org/motechproject/nms/region/controller/LocationDataImportController.java, region/src/main/resources/META-INF/spring/blueprint.xml, testing/pom.xml, testing/src/main/java/org/motechproject/nms/testing/service/impl/TestingServiceImpl.java, testing/src/main/resources/META-INF/spring/blueprint.xml, testing/src/test/java/org/motechproject/nms/testing/it/csv/CsvAuditServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/imi/ImiControllerCdrBundleIT.java
Records all CSV insert/update interactions in the database.
=> Partial fix for #142

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java
Return the subscription from processSubscriptionForBeneficiary in all cases.
cc @llavoie
=> Fixes NMS-207

testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java
Renable and fix the test for NMS-208
=> For NMS-208

testing/src/test/java/org/motechproject/nms/testing/it/api/KilkariControllerBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java
Renable tests and in some cases update the expected result since we also return an error for the parent field.
I may have included changes for NMS-208 in this work as well due to sloppy branch management.  oops
=> NMS-188, NMS-185

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java
Make DOB and LMP optional so the validation code can handle them.
cc @llavoie
=> Fixes NMS-206

testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java
=> Verified fixes for verifyFT286() method and modified test case according

testing/src/test/java/org/motechproject/nms/testing/it/api/KilkariControllerBundleIT.java
Not as much a fix as NMS-178 was closed as invalid.
So I just removed the FT for it.
=> Fixes NMS-178

api/src/main/java/org/motechproject/nms/api/web/BaseController.java, api/src/main/java/org/motechproject/nms/api/web/KilkariController.java, api/src/main/java/org/motechproject/nms/api/web/LanguageController.java, api/src/main/java/org/motechproject/nms/api/web/UserController.java, flw/src/main/java/org/motechproject/nms/flw/service/impl/FrontLineWorkerServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/api/LanguageControllerBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/api/UserControllerBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryUpdateServiceBundleIT.java
Check service deployment regardless of existence of user record in database.
=> Fixes NIP-59

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryUpdateServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java
Allow State and District to be optional during csv import, but still reject with error.
=> Fixes NMS-228

flw/src/main/java/org/motechproject/nms/flw/web/FrontLineWorkerImportController.java, kilkari/src/main/java/org/motechproject/nms/kilkari/web/MctsBeneficiaryImportController.java, region/src/main/java/org/motechproject/nms/region/controller/LanguageLocationImportController.java, region/src/main/java/org/motechproject/nms/region/controller/LocationDataImportController.java
Call getOriginalFilename instead of getName
=> Fixes NMS-229

flw/src/main/java/org/motechproject/nms/flw/domain/CallContent.java, flw/src/main/java/org/motechproject/nms/flw/domain/CallDetailRecord.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscriber.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java, region/src/main/java/org/motechproject/nms/region/domain/Circle.java, region/src/main/java/org/motechproject/nms/region/domain/District.java, region/src/main/java/org/motechproject/nms/region/domain/HealthBlock.java, region/src/main/java/org/motechproject/nms/region/domain/HealthFacility.java, region/src/main/java/org/motechproject/nms/region/domain/HealthSubFacility.java, region/src/main/java/org/motechproject/nms/region/domain/State.java, region/src/main/java/org/motechproject/nms/region/domain/Taluka.java, region/src/main/java/org/motechproject/nms/region/domain/Village.java
This allows for the creation and association of States, Districts, Circles and Languages.  
I was able to create a subscriber, but the number of related tables made creation of all fields through the UI problematic.  I also think there may be an issue in MDS when creating a sub-class (I recieved an error trying to create MctsChild about no such field)
There isn't a requirement for creation of this data through the UI though so I don't feel like we need to fix all of those issues.
=> Fixes NIP-34

imi/src/main/java/org/motechproject/nms/imi/domain/CallDetailRecord.java, imi/src/main/java/org/motechproject/nms/imi/repository/CallDetailRecordDataService.java, imi/src/main/java/org/motechproject/nms/imi/service/impl/CdrFileServiceImpl.java, imi/src/main/java/org/motechproject/nms/imi/service/impl/CsvHelper.java, imi/src/main/resources/META-INF/spring/blueprint.xml, imi/src/test/java/org/motechproject/nms/imi/ut/CsvHelperUnitTest.java, testing/src/main/java/org/motechproject/nms/testing/service/impl/TestingServiceImpl.java, testing/src/main/resources/META-INF/spring/blueprint.xml, testing/src/test/java/org/motechproject/nms/testing/it/imi/CdrFileServiceBundleIT.java
Now makes a copy of the complete CDR in a new CallDetailRecord (nms_imi_cdrs) table for reporting purposes.
=> Fixes #476

testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java
Removed @Ignore for Jira-issue https://applab.atlassian.net/browse/NMS-228 which has been fixed.
=> Removed @Ignore for Jira-issue

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java
Given a subscribers district attempt to find their circle and assign it to them.
=> Fixes NIP-64

testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java
FYI this is failing for me locally, but I don't believe it
cc @frankhuster
=> Here's your IT Frank!  

imi/src/main/java/org/motechproject/nms/imi/service/impl/CsvHelper.java
CallAnswerTime is optional in the CDR file so if it isn't provided don't return InvalidArgument
=> Fixes NIP-67

kilkari/src/main/java/org/motechproject/nms/kilkari/domain/SubscriptionError.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriberService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryUpdateServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java
I haven't tested this or anything -- but I'm having the feeling I won't have a chance to finish it as it appears to be go time. :) If someone could take it over, that would be great.
=> CR feedback from MCTS update work item

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java
=> Added test-case

api/src/test/java/org/motechproject/nms/api/utils/SubscriptionPackBuilder.java, imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/SubscriptionPackMessage.java, kilkari/src/main/java/org/motechproject/nms/kilkari/repository/SubscriptionDataService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/InboxServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java, kilkari/src/test/java/org/motechproject/nms/kilkari/ut/SubscriptionUnitTest.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/SubscriptionServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/utils/SubscriptionHelper.java
Changes Kilkari message retrieval to fix the bugs.
=> Fix for NIP-42-61-70

flw/src/main/java/org/motechproject/nms/flw/domain/ServiceUsageCap.java, flw/src/main/java/org/motechproject/nms/flw/domain/WhitelistEntry.java, flw/src/main/java/org/motechproject/nms/flw/domain/WhitelistState.java, props/pom.xml, props/src/main/java/org/motechproject/nms/props/domain/DeployedService.java
Add change tracking annotations to property/config entities.
=> Fixes #467

api/src/main/java/org/motechproject/nms/api/web/MobileAcademyController.java
Remove the header from the spring MVC annotation
=> Fixes NMS-223

api/src/main/java/org/motechproject/nms/api/web/MobileAcademyController.java
=> Fixes NMS-223 (I think)

region/src/main/java/org/motechproject/nms/region/csv/CircleImportService.java, region/src/main/java/org/motechproject/nms/region/csv/impl/CircleImportServiceImpl.java, region/src/main/resources/META-INF/spring/blueprint.xml, testing/src/test/java/org/motechproject/nms/testing/it/region/CircleImportServiceBundleIT.java, testing/src/test/resources/csv/circles.csv
Create a way to import circles
=> Fixes #430

api/src/main/java/org/motechproject/nms/api/web/converter/MobileAcademyConverter.java, testing/src/test/java/org/motechproject/nms/testing/it/api/MobileAcademyControllerBundleIT.java
=> Fixing bug for empty bookmark fetch

api/src/main/java/org/motechproject/nms/api/web/MobileAcademyController.java, testing/src/test/java/org/motechproject/nms/testing/it/api/MobileAcademyControllerBundleIT.java
=> Fix for validating bad CallId

kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/SubscriptionServiceBundleIT.java
When setting subscription start date use the time at midnight.
=> Fixes NIP-73

api/src/main/java/org/motechproject/nms/api/web/CallDetailsController.java, testing/src/test/java/org/motechproject/nms/testing/it/api/CallDetailsControllerBundleIT.java
Check if mkCardCode is null or empty
=> Fixes NMS-237

api/src/main/java/org/motechproject/nms/api/web/BaseController.java, api/src/main/java/org/motechproject/nms/api/web/MobileAcademyController.java, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/MobileAcademyServiceImpl.java, mobile-academy/src/test/java/org/motechproject/nms/mobileacademy/ut/MobileAcademyServiceUnitTest.java, testing/src/test/java/org/motechproject/nms/testing/it/api/MobileAcademyControllerBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/ma/MobileAcademyServiceBundleIT.java
=> Fixes for final bookmark and score validation

region/src/main/java/org/motechproject/nms/region/controller/LocationDataImportController.java, region/src/main/java/org/motechproject/nms/region/csv/CircleImportService.java
Add circleImportService to the url -> service mapping
=> Fixes NMS-242

api/src/main/java/org/motechproject/nms/api/web/CallDetailsController.java, flw/src/main/java/org/motechproject/nms/flw/domain/CallContent.java
=> Fixes for MA call details storage

api/src/main/resources/securityRules.json, flw/src/main/resources/securityRules.json, imi/src/main/resources/securityRules.json
=> Security Settings

api/src/main/java/org/motechproject/nms/api/web/BaseController.java, api/src/main/java/org/motechproject/nms/api/web/CallDetailsController.java, api/src/main/java/org/motechproject/nms/api/web/MobileAcademyController.java, flw/src/main/java/org/motechproject/nms/flw/domain/CallContent.java, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/MobileAcademyServiceImpl.java, mobile-academy/src/test/java/org/motechproject/nms/mobileacademy/ut/MobileAcademyServiceUnitTest.java, region/src/main/java/org/motechproject/nms/region/controller/LocationDataImportController.java, region/src/main/java/org/motechproject/nms/region/csv/CircleImportService.java, testing/src/test/java/org/motechproject/nms/testing/it/api/MobileAcademyControllerBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/ma/MobileAcademyServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/region/CircleImportServiceBundleIT.java
Implemented FT 262
JIRA https://applab.atlassian.net/browse/NMS-242
=> Implemented FT 262

api/src/main/java/org/motechproject/nms/api/web/BaseController.java, api/src/main/java/org/motechproject/nms/api/web/CallDetailsController.java, api/src/main/java/org/motechproject/nms/api/web/KilkariController.java, api/src/main/java/org/motechproject/nms/api/web/contract/LogHelper.java, api/src/main/java/org/motechproject/nms/api/web/contract/mobileAcademy/sms/DeliveryInfo.java
Fixes the symptoms reported in NMS-246, although the expected workflow in the bug is incorrect.
=> Added check for flw state transition

flw/src/main/java/org/motechproject/nms/flw/service/FrontLineWorkerService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriberService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriptionService.java, tracking/src/main/java/org/motechproject/nms/tracking/service/impl/TrackChangesServiceImpl.java
Fixes that will be needed after http://review.motechproject.org/#/c/5416/ merge.
=> Fix for recent (incoming) MOTECH changes

imi/src/main/java/org/motechproject/nms/imi/service/impl/CdrFileServiceImpl.java, imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/imi/CdrFileServiceBundleIT.java
And makes an unrelated IT slightly better
=> Fixes NIP-92

imi/src/main/java/org/motechproject/nms/imi/service/impl/CdrFileServiceImpl.java
Expect 200 from IMI instead of 202
=> Fixes NIP-90

flw/src/main/java/org/motechproject/nms/flw/service/impl/FrontLineWorkerImportServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/flw/FrontLineWorkerUpdateImportServiceBundleIT.java
If the user has a langauge set, leave it
=> Fixes NMS-255

api/src/main/java/org/motechproject/nms/api/web/contract/mobileAcademy/sms/DeliveryInfo.java
Verify address is not null before obscuring it
=> Fixes NMS-254

kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscriber.java
I think jackson is trying to serialiaze a getter that we don't need it to.  I annotated it with @JsonIgnore
=> Fixes NIP-106

api/src/main/java/org/motechproject/nms/api/web/BaseController.java, api/src/main/java/org/motechproject/nms/api/web/CallDetailsController.java, api/src/main/java/org/motechproject/nms/api/web/KilkariController.java, api/src/main/java/org/motechproject/nms/api/web/LanguageController.java, api/src/main/java/org/motechproject/nms/api/web/MobileAcademyController.java, api/src/main/java/org/motechproject/nms/api/web/UserController.java, api/src/main/java/org/motechproject/nms/api/web/contract/FlwUserResponse.java, api/src/main/java/org/motechproject/nms/api/web/contract/kilkari/InboxResponse.java, api/src/main/java/org/motechproject/nms/api/web/contract/kilkari/InboxSubscriptionDetailResponse.java, api/src/main/java/org/motechproject/nms/api/web/contract/kilkari/KilkariUserResponse.java, api/src/main/java/org/motechproject/nms/api/web/contract/mobileAcademy/CourseResponse.java, api/src/main/java/org/motechproject/nms/api/web/contract/mobileAcademy/CourseVersionResponse.java, api/src/main/java/org/motechproject/nms/api/web/contract/mobileAcademy/GetBookmarkResponse.java, imi/src/main/java/org/motechproject/nms/imi/web/ImiController.java
We now log the response as well as the request on API calls.
=> Fixes NIP-105

flw/src/main/java/org/motechproject/nms/flw/service/impl/FrontLineWorkerImportServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/flw/FrontLineWorkerImportServiceBundleIT.java
If values aren't provided in the import don't save them in the FLW record.
=> Fixes NMS-253

api/src/main/java/org/motechproject/nms/api/web/UserController.java, testing/src/test/java/org/motechproject/nms/testing/it/api/UserControllerBundleIT.java
Fixes #NIP-114 with checks for different scenarios described in the ticket. Either use MCTS data for deployment validation or use current circle if available.
=> Fixes deployment checks for subsciber data

flw/src/main/java/org/motechproject/nms/flw/service/FlwSettingsService.java, flw/src/main/java/org/motechproject/nms/flw/service/impl/FlwSettingsServiceImpl.java, flw/src/main/resources/META-INF/spring/blueprint.xml, testing/src/test/java/org/motechproject/nms/testing/it/flw/FrontLineWorkerServiceBundleIT.java
Implemented NMS_FT_548
JIRA: https://applab.atlassian.net/browse/NMS-257
=> Implemented NMS_FT_548

imi/src/main/java/org/motechproject/nms/imi/service/impl/CdrFileServiceImpl.java
Manjot wondered if we sent notification in case of errors.
I checked, and while it looks like we did for most, we didn't for all.
So I changed the logic.
=> Better CDRFileProcessedNotification

imi/src/main/java/org/motechproject/nms/imi/service/SmsNotificationService.java, imi/src/main/java/org/motechproject/nms/imi/service/impl/SmsNotificationServiceImpl.java, imi/src/main/resources/imi.properties, mobile-academy/pom.xml, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/CourseNotificationServiceImpl.java, mobile-academy/src/main/resources/META-INF/motech/applicationContext.xml, mobile-academy/src/main/resources/META-INF/spring/blueprint.xml, mobile-academy/src/main/resources/sms-content.properties, mobile-academy/src/test/java/org/motechproject/nms/mobileacademy/ut/MobileAcademyServiceUnitTest.java, testing/src/test/java/org/motechproject/nms/testing/it/flw/FrontLineWorkerServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/ma/MobileAcademyServiceBundleIT.java
Fixes #284 
Not the most elegant solution with having the content in a properties file since they would ideally live in IMI's cms system. This is a start that can be optimized further though.
=> Build sms content for completion

imi/src/main/java/org/motechproject/nms/imi/service/impl/ExponentialRetrySender.java
This constructs an SSLConnectionFactory with TLS v1, v1.1 & v1.2 enabled.
=> Potential fix for NIP-140

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/api/KilkariControllerBundleIT.java
fixing data fetch and update timing bug
=> Update data fetch bug

imi/src/main/java/org/motechproject/nms/imi/service/impl/SmsNotificationServiceImpl.java, imi/src/main/resources/imi.properties
=> Adding auth key header for IMI CR request

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java, testing/src/test/resources/csv/nip94.csv
If there is an IVR originated subscriber, when the mcts upload comes, update the subscriber.
=> Fixes NIP-94

mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/CourseNotificationServiceImpl.java, mobile-academy/src/main/resources/sms-content.properties, testing/src/test/java/org/motechproject/nms/testing/it/ma/MobileAcademyServiceBundleIT.java
=> Bug fix for sms content generation

imi/src/main/resources/smsTemplate.json, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/CourseNotificationServiceImpl.java, mobile-academy/src/main/resources/sms-content.properties
=> Fixing sms content format string

checkstyle.xml, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/web/MctsBeneficiaryImportController.java, performance/data/data.py, suppressions.xml, testing/src/main/java/org/motechproject/nms/testing/service/TestingService.java, testing/src/main/java/org/motechproject/nms/testing/service/impl/MctsHelper.java, testing/src/main/java/org/motechproject/nms/testing/service/impl/TestingServiceImpl.java, testing/src/main/java/org/motechproject/nms/testing/web/TestingController.java, testing/src/test/java/org/motechproject/nms/testing/it/testing/BundleIT.java
Fire up MOTECH.
Reset the db & create domain data and then create a file containing 1000 children, in your mim repo directory root:
```
python performance/data/data.py --cleardb --mctskids=1000
```
Import the generated file using MOTECH, and assuming tomcat7 is installed as a service:
```
curl -v -F "csvFile=@/var/lib/tomcat7/testing-directory/mctskids.csv" http://localhost:8080/motech-platform-server/module/kilkari/child/import
```
=> generate sample mcts kids

imi/src/main/resources/imi.properties
Such that by default, MOTECH will be setup to talk to the mock OBD system
=> Slightly more useful default values

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, testing/src/main/java/org/motechproject/nms/testing/service/impl/MctsHelper.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java, testing/src/test/resources/csv/child.txt, testing/src/test/resources/csv/mother.txt, testing/src/test/resources/csv/nip94.csv
Remove file headers for MCTS inserts.
=> Fixes #594

imi/src/main/java/org/motechproject/nms/imi/web/ImiController.java
Changes runtime exception responses to 5xx
=> Adding handler for RuntimeException

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java
Make child name optional in mcts child import
=> Fixes #607

flw/src/main/java/org/motechproject/nms/flw/service/impl/FrontLineWorkerImportServiceImpl.java
=> Obscuring msisdn from csv exception log

api/src/main/java/org/motechproject/nms/api/web/UserController.java
=> Updating log for incoming requests

mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/domain/CompletionRecord.java, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/CourseNotificationServiceImpl.java, mobile-academy/src/main/resources/META-INF/spring/blueprint.xml, mobile-academy/src/main/resources/sms-content.properties, mobile-academy/src/test/java/org/motechproject/nms/mobileacademy/ut/MobileAcademyServiceUnitTest.java, testing/src/test/java/org/motechproject/nms/testing/it/ma/MobileAcademyServiceBundleIT.java
Adding sms reference number for reporting
=> Adding sms reference number for MA reporting

flw/src/main/java/org/motechproject/nms/flw/service/impl/FrontLineWorkerImportServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/flw/FrontLineWorkerImportServiceBundleIT.java, testing/src/test/resources/csv/flw_update_state_by_msisdn.txt
The code wasn't looking to see if mcts id was set or not before checking to see if it matched the
id provided in the csv.
=> Fixes NIP-166

mobile-academy/src/main/resources/nmsCourse.json
The quiz answers updated based on the excel sent to us by bbc
[MOBILE ACADEMY QUIZ.XLSX](https://github.com/motech-implementations/mim/files/11122/MOBILE.ACADEMY.QUIZ.XLSX)
=> Updating quiz answers from bbc

imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java
Should make generateFreshCalls faster
=> Remove calls to getDetachedField in generateFreshCalls

imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriptionService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
activatePendingSubscriptionsUpTo uses a single update query
not calling getDetachedField on subscriber language & circle
simplified list operations in findActiveSubscriptionsForDay
=> NIP-177 - perf improvements

imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriptionService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
Reverts motech-implementations/mim#615
=> Revert "NIP-177 - perf improvements"

imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java, imi/src/main/resources/imi.properties, kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriptionService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java, kilkari/src/main/resources/META-INF/motech/applicationContext.xml, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/SubscriptionServiceBundleIT.java
Use a single update query to activate subscriptions
Stop using getDetachedField in the generateTargetFile loop
Remove caching for getSubscriptionPacks
=> NIP-177 - Perf work

imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriptionService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
Paging based on id + LIMIT instead of LIMIT + OFFSET
=> Faster fresh call generation

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
Slightly more discriminant cache eviction.
Will build when the necessary change in motech/0.27.X is merged & built
=> Catching up with Pawel's cache evict work on master branch

api/pom.xml, csv/pom.xml, flw/pom.xml, imi/pom.xml, kilkari/pom.xml, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/SubscriptionPack.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/CsrServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java, mobile-academy/pom.xml, pom.xml, props/pom.xml, region/pom.xml, testing/pom.xml, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/CsrServiceBundleIT.java, tracking/pom.xml
Fixes NIP-184 with query update for fresh calls
=> Soft launch bugfix

api/pom.xml, csv/pom.xml, flw/pom.xml, imi/pom.xml, kilkari/pom.xml, mobile-academy/pom.xml, pom.xml, props/pom.xml, region/pom.xml, testing/pom.xml, tracking/pom.xml
=> Preparing the v1.0.2 release

api/pom.xml, csv/pom.xml, flw/pom.xml, imi/pom.xml, imi/src/main/java/org/motechproject/nms/imi/domain/ChunkAuditRecord.java, imi/src/main/java/org/motechproject/nms/imi/exception/ChunkingException.java, imi/src/main/java/org/motechproject/nms/imi/repository/ChunkAuditRecordDataService.java, imi/src/main/java/org/motechproject/nms/imi/repository/CsrProcessingAuditDataService.java, imi/src/main/java/org/motechproject/nms/imi/service/CdrFileService.java, imi/src/main/java/org/motechproject/nms/imi/service/impl/CdrFileServiceImpl.java, imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java, imi/src/main/resources/META-INF/spring/blueprint.xml, imi/src/main/resources/imi.properties, kilkari/pom.xml, mcts/pom.xml, mobile-academy/pom.xml, pom.xml, props/pom.xml, region/pom.xml, testing/pom.xml, tracking/pom.xml
A new imi.properties setting enables chunk CSR processing:
```
imi.csr_chunk_size
```
Its default value is 1, which means no chunking.
Any other value will distribute CSR in chunks for processing.
=> CDR chunking

mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/CourseNotificationServiceImpl.java
reusing the message from the exception thrown from down under
=> Better alert description

api/pom.xml, csv/pom.xml, flw/pom.xml, imi/pom.xml, imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java, kilkari/pom.xml, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/CsrVerifierServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java, mcts/pom.xml, mcts/src/main/java/org/motechproject/nms/mcts/service/impl/MctsWsImportServiceImpl.java, mobile-academy/pom.xml, pom.xml, props/pom.xml, region/pom.xml, testing/pom.xml, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/CsrServiceBundleIT.java, tracking/pom.xml
=> Circle 99 & MCTS fixes

api/pom.xml, csv/pom.xml, flw/pom.xml, imi/pom.xml, kilkari/pom.xml, kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriberService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java, mcts/pom.xml, mobile-academy/pom.xml, pom.xml, props/pom.xml, region/pom.xml, testing/pom.xml, testing/src/test/java/org/motechproject/nms/testing/it/imi/TargetFileServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/InboxServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryUpdateServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/SubscriptionServiceBundleIT.java, tracking/pom.xml
=> Ivr subscription update

kilkari/src/main/java/org/motechproject/nms/kilkari/domain/Subscription.java, testing/src/main/java/org/motechproject/nms/testing/service/impl/TestingServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/SubscriptionServiceBundleIT.java
Now tracks the startDate field of the Subscription entity
=> Fixes NIP-303

imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/imi/TargetFileServiceBundleIT.java
By ignoring subscriptions on their last day from fresh calls during generateTargetFile
=> Fixes NMS-301

mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/CourseNotificationServiceImpl.java, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/MobileAcademyServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/ma/MobileAcademyServiceBundleIT.java
Fixes NIP-317 with creation of new activity record for second attempt
=> Fixes NIP-317 - Activity count

imi/src/main/java/org/motechproject/nms/imi/service/impl/CdrFileServiceImpl.java, testing/src/test/java/org/motechproject/nms/testing/it/imi/CdrFileServiceBundleIT.java
By inserting a record for each detail & summary file after
successfully verifying them, and also inserting a record for each file
after successfully or unsuccessfully notifying IMI
=> Fixes NIP-205

api/pom.xml, csv/pom.xml, flw/pom.xml, imi/pom.xml, kilkari/pom.xml, mcts/pom.xml, mobile-academy/pom.xml, pom.xml, props/pom.xml, region/pom.xml, testing/pom.xml, tracking/pom.xml
=> Upgrading pom versions for next release

api/pom.xml, csv/pom.xml, flw/pom.xml, imi/pom.xml, kilkari/pom.xml, mcts/pom.xml, mobile-academy/pom.xml, pom.xml, props/pom.xml, region/pom.xml, testing/pom.xml, tracking/pom.xml
=> Bumping version for next release/hotfix

api/src/main/java/org/motechproject/nms/api/web/OpsController.java, kilkari/src/main/java/org/motechproject/nms/kilkari/handler/SubscriptionManagerHandler.java, kilkari/src/main/resources/kilkari.properties, pom.xml
Adding logging trail for subscription upkeep listener and removing transactional from listener
=> Subscriptions upkeep

api/src/main/java/org/motechproject/nms/api/web/UserController.java, flw/src/main/java/org/motechproject/nms/flw/domain/FrontLineWorkerStatus.java, testing/src/test/java/org/motechproject/nms/testing/it/api/UserControllerBundleIT.java
implements NMS-325 to restrict MA access to anonymous users
=> Restrict MA anonymous

api/src/main/java/org/motechproject/nms/api/web/OpsController.java, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/MobileAcademyService.java, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/MobileAcademyServiceImpl.java, pom.xml, testing/src/test/java/org/motechproject/nms/testing/it/api/OpsControllerBundleIT.java
This should expose a get endpoint to fetch scores inside bookmark for a calling number
=> Ops helper to look at scores in bookmarks

api/src/main/java/org/motechproject/nms/api/web/OpsController.java, csv/src/main/java/org/motechproject/nms/csv/utils/GetLocalDate.java, flw/src/main/java/org/motechproject/nms/flw/service/impl/FrontLineWorkerImportServiceImpl.java, flw/src/main/java/org/motechproject/nms/flw/web/FrontLineWorkerImportController.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/SubscriptionRejectionReason.java, kilkari/src/main/java/org/motechproject/nms/kilkari/exception/MultipleSubscriberException.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriberService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/utils/KilkariConstants.java, kilkari/src/main/java/org/motechproject/nms/kilkari/web/MctsBeneficiaryImportController.java, testing/src/test/java/org/motechproject/nms/testing/it/flw/FrontLineWorkerImportServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/flw/FrontLineWorkerUpdateImportServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryUpdateServiceBundleIT.java, testing/src/test/resources/csv/flw.txt, testing/src/test/resources/csv/flw_FT_558.txt, testing/src/test/resources/csv/flw_FT_560.txt, testing/src/test/resources/csv/flw_FT_561.txt, testing/src/test/resources/csv/flw_location_update_msisdn.txt, testing/src/test/resources/csv/flw_name_missing.txt, testing/src/test/resources/csv/flw_update_state_by_msisdn.txt
=> Fixing the bug, when ACTIVE child is present, mother should stay deactivated

api/pom.xml, csv/pom.xml, flw/pom.xml, flwUpdate/pom.xml, imi/pom.xml, kilkari/pom.xml, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, mcts/pom.xml, mobile-academy/pom.xml, pom.xml, props/pom.xml, region/pom.xml, testing/pom.xml, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java, tracking/pom.xml
NMS-371 - Include Modified Date in Kilkari Beneficiary CSV Import
=> Added Last_Update_date to mapping of csvReader

api/pom.xml, csv/pom.xml, flw/pom.xml, flwUpdate/pom.xml, imi/pom.xml, kilkari/pom.xml, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/utils/KilkariConstants.java, mcts/pom.xml, mobile-academy/pom.xml, pom.xml, props/pom.xml, region/pom.xml, testing/pom.xml, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryUpdateServiceBundleIT.java, testing/src/test/resources/csv/mcts_beneficiary_update.csv, tracking/pom.xml
NMS-374 Refactor Kilkari CSV Import so that the whole import is not halted because of an error in a single record
=> Csv import fix

api/pom.xml, csv/pom.xml, flw/pom.xml, flwUpdate/pom.xml, imi/pom.xml, kilkari/pom.xml, kilkari/src/main/java/org/motechproject/nms/kilkari/handler/SubscriptionManagerHandler.java, mcts/pom.xml, mobile-academy/pom.xml, pom.xml, props/pom.xml, region/pom.xml, testing/pom.xml, tracking/pom.xml
Removed the purging method call.
=> NMS-375 Stop purging of deactivated subscritions

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java
I've fixed the bug where child with mother null is overriding previous mother, if present
=> child update with mother null bug fix

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryValueProcessorImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/LocationServiceImpl.java
Fixed Error Causing code after initial testing
=> feature_nic_new_locations

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryValueProcessorImpl.java, mcts/src/main/java/org/motechproject/nms/mcts/service/impl/MctsWebServiceFacadeImpl.java, rch/src/main/java/org/motechproject/nms/rch/service/impl/RchWebServiceFacadeImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/LocationServiceImpl.java
Added code to trim extra spaces in Taluka code
=> extra_spaces_in_taluka_code_fix

imi/src/main/java/org/motechproject/nms/imi/domain/CallDetailRecord.java, imi/src/main/java/org/motechproject/nms/imi/service/impl/CdrFileServiceImpl.java
Increased cdr processing performance by adding bulk insert code
=> Cdr processing performance

api/src/main/java/org/motechproject/nms/api/web/service/impl/BeneficiaryUpdateServiceImpl.java, rch/src/main/java/org/motechproject/nms/rch/service/impl/RchWebServiceFacadeImpl.java
code to handle 620 mctsId's having nonunique (mctsflwid,stateId) while updating asha locations
=> asha location update fix for non unique (mctsid,stateid)

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryValueProcessorImpl.java, rch/src/main/java/org/motechproject/nms/rch/service/impl/RchWebServiceFacadeImpl.java
Fixed Persistence manager and pre-persist errors in RCH XML read
=> RCH Bug Fixes

region/src/main/java/org/motechproject/nms/region/service/impl/LocationServiceImpl.java
partitioned villages, health-facilities, health-sub-facilities queries with partition-size 2000
=> partitioned villages, health-facilities, health-sub-facilities queries

region/src/main/java/org/motechproject/nms/region/domain/HealthBlock.java, region/src/main/java/org/motechproject/nms/region/domain/HealthSubFacility.java, region/src/main/java/org/motechproject/nms/region/domain/Taluka.java, region/src/main/java/org/motechproject/nms/region/domain/Village.java
Added many-many relation fields to default fetch group
=> RCH beneficiary import performance

Database Instructions.txt, imi/src/main/java/org/motechproject/nms/imi/domain/CallSummaryRecord.java, imi/src/main/java/org/motechproject/nms/imi/service/impl/CdrFileServiceImpl.java
increased csr processing performance by adding bulk insert and added unique requestID
=> CSR Processing Performance

testing/src/test/java/org/motechproject/nms/testing/it/api/UserControllerBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/RchBeneficiaryImportServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/kilkari/SubscriptionServiceBundleIT.java, testing/src/test/java/org/motechproject/nms/testing/it/rch/RchWebServiceFacadeBundleIT.java, testing/src/test/resources/rch/RCH_StateID_21_Child_Response.xml
=> Written_PITS_For_Bugs

imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java
Setting high priority for records written to JH obd file
=> Obd file bifurcation

region/src/main/java/org/motechproject/nms/region/domain/HealthBlock.java, region/src/main/java/org/motechproject/nms/region/domain/HealthFacility.java, region/src/main/java/org/motechproject/nms/region/domain/HealthSubFacility.java, region/src/main/java/org/motechproject/nms/region/domain/Taluka.java, region/src/main/java/org/motechproject/nms/region/domain/TalukaHealthBlock.java, region/src/main/java/org/motechproject/nms/region/domain/Village.java, region/src/main/java/org/motechproject/nms/region/domain/VillageHealthSubFacility.java, region/src/main/java/org/motechproject/nms/region/service/impl/HealthBlockServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/HealthFacilityServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/HealthSubFacilityServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/TalukaServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/VillageServiceImpl.java
Updated unique keys for locations to ensure a location code is unique in one state.
=> Locations codes key update

kilkari/src/main/java/org/motechproject/nms/kilkari/service/MctsBeneficiaryImportService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportReaderServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java, kilkari/src/main/resources/kilkari.properties, mcts/src/main/java/org/motechproject/nms/mcts/service/impl/MctsWsImportServiceImpl.java, rch/src/main/java/org/motechproject/nms/rch/service/impl/RchWebServiceFacadeImpl.java
NIC Mother and Child data will now be processed in chunks(configurable). After each chunk, number of active subscriptions in db will be checked, and a boolean will be set to reflect whether sub cap has been reached. If yes, all further subscriptions will be put on HOLD. Capacity check has also been added when subscriptions are reactivated, and when the start date is being updated.
=> Sub cap 25lakh issue final

region/src/main/java/org/motechproject/nms/region/service/impl/DistrictServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/HealthBlockServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/HealthFacilityServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/HealthSubFacilityServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/TalukaServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/VillageServiceImpl.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/domain/VillageImportRejection.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/DistrictRejectionService.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/HealthBlockRejectionService.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/HealthFacilityRejectionService.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/HealthSubFacilityRejectionService.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/TalukaRejectionService.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/VillageRejectionService.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/DistrictRejectionServiceImpl.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/HealthBlockRejectionServiceImpl.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/HealthFacilityRejectionServiceImpl.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/HealthSubFacilityRejectionServiceImpl.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/TalukaRejectionServiceImpl.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/VillageRejectionServiceImpl.java
Update code for location id null issue
=> Final location rejection handling

api/pom.xml, api/src/main/resources/META-INF/motech/applicationContext.xml, imi/pom.xml, imi/src/main/java/org/motechproject/nms/imi/web/ImiController.java, imi/src/main/resources/META-INF/motech/applicationContext.xml, kilkari/pom.xml, kilkari/src/main/java/org/motechproject/nms/kilkari/service/RateLimitInterceptor.java, kilkari/src/main/resources/kilkari.properties, pom.xml
Implemented ratelimiting for necessary api's using interceptor.
=> Rate limiting final Fix

region/src/main/java/org/motechproject/nms/region/controller/LocationDataImportController.java, region/src/main/java/org/motechproject/nms/region/csv/LanguageLocationImportService.java, region/src/main/java/org/motechproject/nms/region/csv/impl/LanguageLocationImportServiceImpl.java
Aim: to create a record in circle table using id value by sequence table.
=> Introduce New api to create circle record

region/src/main/java/org/motechproject/nms/region/controller/LocationDataImportController.java, region/src/main/resources/securityRules.json
=> new api to create circle

imi/src/main/java/org/motechproject/nms/imi/web/ImiController.java
by this fix we can process cdr/csr multiple times in a day
=> splitting_cdr_csr

region/src/main/java/org/motechproject/nms/region/controller/LocationDataImportController.java, region/src/main/java/org/motechproject/nms/region/csv/LanguageLocationImportService.java, region/src/main/java/org/motechproject/nms/region/csv/impl/LanguageLocationImportServiceImpl.java
Created New api for state creation.
=> new api to create state

flwUpdate/src/main/java/org/motechproject/nms/flwUpdate/service/impl/FrontLineWorkerImportServiceImpl.java, rch/src/main/java/org/motechproject/nms/rch/service/impl/RchWebServiceFacadeImpl.java
Bug fix : Deactivate asha - mobile number linked with asha already present with active job status. 
With current changes job status for asha changes to INACTIVE and mobile number updated.
=> Bug fix : Flw deactivate asha with active msisdn

flw/src/main/java/org/motechproject/nms/flw/exception/FlwExistingMobileNumberAlreadySubscribedException.java, flwUpdate/src/main/java/org/motechproject/nms/flwUpdate/service/FrontLineWorkerImportService.java, flwUpdate/src/main/java/org/motechproject/nms/flwUpdate/service/impl/FrontLineWorkerImportServiceImpl.java, rch/src/main/java/org/motechproject/nms/rch/service/impl/RchWebServiceFacadeImpl.java
Added rejection reason 'Updated_Record_Already_Exists' for FLW
=> Bug_fix : FLW rejection - Updated record already exists added

kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java, rch/src/main/java/org/motechproject/nms/rch/service/impl/RchWebServiceFacadeImpl.java
Location not getting to process due to unwanted message in case of failure; Also few health block has been added in priority blocks of upkeep
=> Location 102 issue and HB priority

imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java, imi/src/main/java/org/motechproject/nms/imi/web/ImiController.java, imi/src/main/resources/imi.properties, kilkari/src/main/java/org/motechproject/nms/kilkari/service/CallRetryService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/CallRetryServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/ChildRejectionServiceImpl.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/MotherRejectionServiceImpl.java
Retry table data data fetching process has been changed for IVR and Normal OBD files
=> IVR target file bifurcation

rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/ChildRejectionServiceImpl.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/MotherRejectionServiceImpl.java
Due to extra char in name(String) and location names, insert query in rejection table is failing. Issue resolved.
=> Bug resolved: Import process issue with location names

kilkari/src/main/java/org/motechproject/nms/kilkari/domain/SubscriptionStatus.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java
added new subscription status 'PACK_NOT_INITIATED_DUE_TO_ON_HOLD_DATA'
=> added new subscription status 'PACK_NOT_INITIATED_DUE_TO_ON_HOLD_DATA'

api/src/main/java/org/motechproject/nms/api/web/KilkariController.java
In Case of Outbound calls, Even when Beneficary is on Hold Status, she should able to listen to their respective week content and their subsciptions should turn to ACTIVE.
=> Hold Subscriptions converted to Active on outbound calls

flw/src/main/java/org/motechproject/nms/flw/domain/FrontLineWorker.java, flw/src/test/java/org/motechproject/nms/flw/ut/ValidFrontLineWorkerUnitTest.java, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/MctsBeneficiary.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/MctsBeneficiaryValueProcessor.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryImportServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/MctsBeneficiaryValueProcessorImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java, kilkari/src/main/java/org/motechproject/nms/kilkari/utils/RejectedObjectConverter.java, region/src/main/java/org/motechproject/nms/region/service/HealthBlockService.java, region/src/main/java/org/motechproject/nms/region/service/HealthFacilityService.java, region/src/main/java/org/motechproject/nms/region/service/HealthSubFacilityService.java, region/src/main/java/org/motechproject/nms/region/service/TalukaService.java, region/src/main/java/org/motechproject/nms/region/service/VillageService.java, region/src/main/java/org/motechproject/nms/region/service/impl/HealthBlockServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/HealthFacilityServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/HealthSubFacilityServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/LocationServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/TalukaServiceImpl.java, region/src/main/java/org/motechproject/nms/region/service/impl/VillageServiceImpl.java, region/src/test/java/org/motechproject/nms/region/ut/FullLocationValidatorUnitTest.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/ChildRejectionServiceImpl.java, rejection-handler/src/main/java/org/motechproject/nms/rejectionhandler/service/impl/MotherRejectionServiceImpl.java
Inlcuded 3 changes
- Kamal's Location breakup changes
- Child import error issue
- Location getting updated in mother accepted table while record getting rejected
=> Location validation constraint

rch/src/main/java/org/motechproject/nms/rch/soap/RchwebservicesLocator.java
Domain name has been changed from NIC side
=> Domain gets changed

imi/src/main/java/org/motechproject/nms/imi/service/impl/TargetFileServiceImpl.java, imi/src/main/resources/META-INF/spring/blueprint.xml, kilkari/src/main/java/org/motechproject/nms/kilkari/domain/SubscriptionTimeSlot.java, kilkari/src/main/java/org/motechproject/nms/kilkari/repository/SubscriptionTimeSlotDataService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/SubscriptionTimeSlotService.java, kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionTimeSlotServiceImpl.java, kilkari/src/main/resources/META-INF/spring/blueprint.xml
Three new columns has been added in target file based on preferred time slot programme
=> Time Slot optimization column in OBD files

rch/src/main/java/org/motechproject/nms/rch/service/impl/RchWsImportServiceImpl.java
Due to SSH exception during the SCP event, we serialize the event calling all 4 APIs in the same event
=> Rch Import event serialized

imi/src/main/java/org/motechproject/nms/imi/service/impl/SmsNotificationServiceImpl.java, imi/src/main/resources/smsTemplate.json, imi/src/test/java/org/motechproject/nms/imi/ut/SmsNotificationServiceUnitTest.java, mobile-academy/src/main/java/org/motechproject/nms/mobileacademy/service/impl/CourseNotificationServiceImpl.java, mobile-academy/src/main/resources/sms-content.properties, mobile-academy/src/test/java/org/motechproject/nms/mobileacademy/ut/CourseNotificationServiceImplUnitTest.java, rch/src/main/java/org/motechproject/nms/rch/service/impl/RchWsImportServiceImpl.java
added a new field messageType to the sms template
=> sms-payload changes

.github/workflows/NMS-deployment.yaml
Tested deployment branch for workflow runs are happening in branch provided to the yaml.
=> Deployment testing
